### ISSUE TITLE
Nergigante lures

### ISSUE THREAD

**Issue by Bigleone** [gianemi2/who-drop-that-lure#3]
Got Ruiner lure form Kushala (tempered)
Should I make a new issue if I find something new?

**Comment by gianemi2** [comment]
Hi and thanks for your report. I’ll create an issue for every missing monsters lure droppers. 
I’ll add every reported monster since now

**Comment by Bigleone** [comment]
Got Ruiner Nergigante  from Tempered Stygian Zinogre

**Comment by gianemi2** [comment]
Updated! Thank you :)
